### ISSUE TITLE
numpy.ndarray' object has no attribute 'split'

### ISSUE THREAD

**Issue by picca** [vasole/pymca#344] opened 2018-10-04 11:54 UTC
Hello Armando, with 5.4.0, I get this error message each time I click on a hdf5 node.

numpy.ndarray' object has no attribute 'split'   File "/usr/lib/python3/dist-packages/PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py", line 618, in hdf5Slot
    ddict['name'])
  File "/usr/lib/python3/dist-packages/PyMca5/PyMcaCore/NexusTools.py", line 467, in getScannedPositioners
    tokens = title.split()

**Comment by vasole** [comment] 2018-10-04 12:09
Problem not reproduced here. 

Any possibility to have access to the file? I suspect the file being not properly written.

**Comment by picca** [comment] 2018-10-04 12:14
We can open it with the 5.1.1

**Comment by vasole** [comment] 2018-10-04 12:38
Yes, but that does not mean the file is properly written.

**Comment by picca** [comment] 2018-10-04 12:40
You are right :)

**Comment by vasole** [comment] 2018-10-04 12:41
The error points to the title being written as an array of strings instead of being written as a string.

**Comment by vasole** [comment] 2018-10-04 12:43
When you open the file in PyMca, do you see square brackets under the description of the entry?

**Comment by picca** [comment] 2018-10-04 12:47
We do not exactly understand what you want.

**Comment by vasole** [comment] 2018-10-04 12:52
Do you see any square bracket in the widget? In the example below there are no square brackets anywhere, in particular under the word "Description".

![image](https://user-images.githubusercontent.com/5636251/46475039-b3558f80-c7e4-11e8-8921-68598a810f9f.png)

In this other example there are square brackets everywhere.

![image](https://user-images.githubusercontent.com/5636251/46475168-17785380-c7e5-11e8-81e9-6effae9cd558.png)

**Comment by picca** [comment] 2018-10-04 12:57
ok, sorry I just read my email and not the github  file  via Firefox.
So I did not saw the images :)

**Comment by picca** [comment] 2018-10-04 13:00
novhere, the only strange think is the description of scan50 which is b'users\n'

Did you received the nxs file, I sent you ?

**Comment by vasole** [comment] 2018-10-04 13:03
I was reading github and not my mail :-) I have received your file. I'm going to look at it.

**Comment by picca** [comment] 2018-10-04 13:09
[b'users\n']
<class 'AttributeError'> 'numpy.ndarray' object has no attribute 'split'   File "/usr/lib/python3/dist-packages/PyMca5/PyMcaGui/io/hdf5/QNexusWidget.py", line 618, in hdf5Slot
    ddict['name'])
  File "/usr/lib/python3/dist-packages/PyMca5/PyMcaCore/NexusTools.py", line 468, in getScannedPositioners
    tokens = title.split()

I just instrumented the code and I get this when I plot the title node

so the problem is with this ['b'users\n']

**Comment by vasole** [comment] 2018-10-04 13:39
Yes, because your title is ['b'users\n'] instead of "users". Whoever writes that file does not do the things properly. Proper ways to write that in python:

h["/scan_50/title"]=u"users"
h["/scan_50/title"]=unicode("users") under python 2.x
h["/scan_50/title"]=b"users".decode("utf-8") under python 3.x

Probably the writing code has done something like numpy.string_(["users"]) under Python 2.

**Comment by vasole** [comment] 2018-10-04 13:39
The PyMca problem should be fixed by #345 but your file is not correct.

**Comment by vasole** [comment] 2018-10-04 13:41
You can update your installation or open your file(s) and patch the title dataset.

**Comment by picca** [comment] 2018-10-04 13:43
No this is generated by the datarecorder system of SOLEIL.
changing this would be quite hard...

**Closed** 2018-10-04 13:43 UTC

**Comment by vasole** [comment] 2018-10-04 13:48
Sorry, it was closed automatically when I merged the pull request.

I'm really fed up with all the relaxations of the NeXus rules. It makes life quite hard for developers. I'm proposing a joined action between NeXpy, silx view and PyMca to make life nasty to the end users so that they put pressure at the writers side because a changing format is a bad format.

**Comment by vasole** [comment] 2018-10-04 14:30
Everything is HDF5 valid.

We'll see if my position is followed at the NIAC in a couple of weeks (I doubt it).

**Comment by vasole** [comment] 2018-10-04 14:33
According to NeXus things are different:

- Strings should be utf-8 and you are writing bytes and sometimes even latin-1
- The problem is some writers are systematically writing arrays of (byte!) strings and instead of correcting at the writing side they have relaxed the NeXus rules and have put the burden at the reader side.

**Comment by picca** [comment] 2018-10-04 15:03
Here the definition

http://download.nexusformat.org/sphinx/nxdl-types.html


```
Data Types allowed in NXDL specifications

Data types for use in NXDL describe the expected type of data for a NeXus field. These terms are very broad. More specific terms are used in actual NeXus data files that describe size and array dimensions. In addition to the types in the following table, the NAPI type is defined when one wishes to permit a field with any of these data types.
ISO8601:	ISO8601 date/time stamp
NX_BINARY:	any representation of binary data - if text, line terminator is [CR][LF]
NX_BOOLEAN:	true/false value ( true | 1 | false | 0 )
NX_CHAR:	

any string representation

All strings are to be encoded in UTF-8.

Includes fixed-length strings, variable-length strings, and string arrays.

Some file writers write strings as a string array of rank 1 and length 1. Clients should be prepared to handle such strings.
NX_DATE_TIME:	alias for the ISO8601 date/time stamp
NX_FLOAT:	any representation of a floating point number
NX_INT:	any representation of an integer number
NX_NUMBER:	any valid NeXus number representation
NX_POSINT:	any representation of a positive integer number (greater than zero)
NX_UINT:	any representation of an unsigned integer number (includes zero)
```

**Comment by vasole** [comment] 2018-10-04 15:06
See

https://github.com/nexusformat/NIAC/issues/31

**Comment by vasole** [comment] 2018-11-15 17:43
Version 5.4.1 is out

BTW the NeXus documentation is updated

NX_CHAR: | The preferred string representation is UTF-8.  Both fixed-length strings and variable-length strings are valid. String arrays cannot be used where only a string is expected (title, start_time, end_time, NX_class attribute,...). Fields or attributes requiring the use of string arrays will be clearly marked as such (like the NXdata attribute auxiliary_signals).
-- | --
