### ISSUE TITLE
Minimal McaAdvancedFit example fails

### ISSUE THREAD

**Issue by alexbjorling** [vasole/pymca#453] opened 2019-04-26 07:49 UTC
Following the example [here](http://www.silx.org/doc/PyMca/5.4.3/recipes/xrfembedpyqt.html) with PyMca 5.4.3 and silx 0.10.1 and Python 2.7.15, the following code

```python
from silx.gui import qt
import sys
import numpy as np
from PyMca5.PyMca import McaAdvancedFit

app = qt.QApplication(sys.argv)

widget = McaAdvancedFit.McaAdvancedFit()
x = np.arange(100)
y = np.random.random(x.shape)
widget.setData(x, y)

```

produces this
```
TypeError                                 Traceback (most recent call last)
/home/alex/tmp/tmp.py in <module>()
      9 x = np.arange(100)
     10 y = np.random.random(x.shape)
---> 11 widget.setData(x, y)

/home/alex/.local/lib/python2.7/site-packages/PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.pyc in setData(self, *var, **kw)
   1821                                                             self.info['xmax']))
   1822         self._updateTop()
-> 1823         self.plot()
   1824 
   1825     def setheader(self, *var, **kw):

/home/alex/.local/lib/python2.7/site-packages/PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.pyc in plot(self, ddict)
   2059                 ydata.shape= [len(ydata),]
   2060                 self.graph.addCurve(xdata, ydata, legend="Data", replace=True)
-> 2061                 self.graph.setActiveCurve("Data")
   2062                 return
   2063             else:

/home/alex/.local/lib/python2.7/site-packages/PyMca5/PyMcaGui/physics/xrf/McaAdvancedFit.pyc in setActiveCurve(self, legend, replot)
   2921         if legend is not None:
   2922             # see vasole/pymca#314
-> 2923             super(McaGraphWindow, self).setActiveCurve(legend, replot)
   2924         self.setGraphYLabel("Counts")
   2925         if self.energyButton.isChecked():

TypeError: setActiveCurve() takes exactly 2 arguments (3 given)
```

Is something broken?

**Comment by woutdenolf** [comment] 2019-04-26 08:03
Yes, the silx API changed since version 0.9.0 (https://github.com/silx-kit/silx/pull/2211). The second argument (`replot`) should be removed.

**Comment by woutdenolf** [comment] 2019-04-26 08:31
It works on the master branch. I assume is was solved by https://github.com/vasole/pymca/pull/441.

**Comment by vasole** [comment] 2019-04-28 16:55
Yes, the problem was introduced by silx 0.10.x

There are significant HDF5 related improvements that we would like to ship with PyMca 5.5.0

Until a new release takes place, you can just fix your installation by changing the offending line. Just removing the replot argument is enough.

**Comment by vasole** [comment] 2019-04-28 17:11
Duplicate of  #434

**Closed by vasole** 2019-04-28 17:11 UTC
