### ISSUE TITLE
[PlotWindow] logarithmic scale with matplotlib 2.1.0

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#125] opened 2017-11-17 17:31 UTC
An exception is raised when plotting zeros in logarithmic scale (works fine for matplotlib <= 2.0.0)

```python
from PyMca5.PyMcaGui.plotting.PlotWindow import PlotWindow
import PyQt4.QtGui as qt

app = qt.QApplication([])
w = PlotWindow()
w.addCurve(range(10),range(10),"test")
w.setYAxisLogarithmic(True)
w.show()
result = app.exec_()
```

**Comment by vasole** [comment] 2017-11-17 17:51
Thanks it seems a duplicate of #79. Already corrected in current master.

At the ESRF the package implementing the changes is already available for installation.

A new PyMca release is expected early next week.

**Comment by vasole** [comment] 2017-11-24 03:45
v5.2.2 released.

**Closed by vasole** 2017-11-24 03:45 UTC
Labels: duplicate
